language: java
jdk: openjdk8

env:
  # Use these to trigger a release. You can also uncomment them in a custom config that you can
  # pass to the manual build trigger (in the web interface).  
  # - NEW_RELEASE_VER=1.0-TEST
  # - NEW_SNAPSHOT_VER='1.0-SNAPSHOT'

install: echo "Skipping default installation step"

script:
  - ./travis/travis.sh

cache:
  directories:
    - $HOME/.m2
