#
# This file is generated by the POM from the copy at /src/main/resources/create-project.sh
#
groupId="$1"
artifactId="$2"
version="$3"

if [[ "$#" < 3 ]]; then
	cat <<EOT


Creates a new Knetminer project from our archetype.  
	
	$(basename $0) <groupId> <artifactId> <version> 

EOT
	exit 1
fi

mvn dependency:get \
  -Dartifact=${project.groupId}:${project.artifactId}:${project.version}\
  -DremoteRepositories=https://knetminer.org/artifactory/repository/maven-public


# First get the archetype definition file, as per
# https://maven.apache.org/archetype/maven-archetype-plugin/archetype-repository.html
#
#settings="/tmp/knetminer-archetype-settings.xml"
#curl -L "https://raw.githubusercontent.com/Rothamsted/knetminer-common/master/knetminer-archetype/settings.xml" \
#     -o "$settings"
     
# So that now we can use it
#
mvn archetype:generate \
	-DgroupId=$groupId -DartifactId=$artifactId -Dversion=$version \
	-DarchetypeGroupId=${project.groupId} \
	-DarchetypeArtifactId=knetminer-archetype \
	-DarchetypeVersion=${project.version} \
	-DinteractiveMode=false 
	#-Dsettings="$settings"
