#
# This file is generated by the POM from the copy at /src/main/resources/create-project.sh
#
groupId="$1"
artifactId="$2"
version="$3"

if [[ "$#" < 3 ]]; then
	cat <<EOT


Creates a new Knetminer project from our archetype.  
	
	$(basename $0) <groupId> <artifactId> <version> 

EOT
	exit 1
fi


# First install the archetype
mvn dependency:get \
  -Dartifact=${project.groupId}:${project.artifactId}:${project.version}\
  -DremoteRepositories=https://knetminer.org/artifactory/repository/maven-public

# So that now we can use it
set -x
yes | mvn archetype:generate \
	-DgroupId=$groupId -DartifactId=$artifactId -Dversion=$version \
	-DarchetypeGroupId=${project.groupId} \
	-DarchetypeArtifactId=knetminer-archetype \
	-DarchetypeVersion=${project.version} \
	-DinteractiveMode=false
	
